In [24]:
from google.colab import files
uploaded = files.upload()
!mkdir -p ~/.kaggle && mv /content/kaggle.json ~/.kaggle

Saving kaggle.json to kaggle.json


In [25]:
!kaggle datasets download -d aemyjutt/diabetesdataanslysis

diabetesdataanslysis.zip: Skipping, found more recently modified local copy (use --force to force download)


In [26]:
from zipfile import ZipFile
with ZipFile("/content/diabetesdataanslysis.zip","r") as zipobj:
  zipobj.extractall()

In [27]:
import pandas as pd
import numpy as np

In [28]:
dataset = pd.read_csv("diabetes.csv")
print(dataset)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                  

In [29]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [30]:
print(X)
print(y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [32]:
print(X_train)
print(X_test)

[[  0.    117.      0.    ...  33.8     0.932  44.   ]
 [  3.    111.     62.    ...  22.6     0.142  21.   ]
 [  5.     44.     62.    ...  25.      0.587  36.   ]
 ...
 [  3.     61.     82.    ...  34.4     0.243  46.   ]
 [  1.     96.    122.    ...  22.4     0.207  27.   ]
 [  1.     90.     62.    ...  25.1     1.268  25.   ]]
[[0.000e+00 1.460e+02 8.200e+01 ... 4.050e+01 1.781e+00 4.400e+01]
 [1.000e+00 1.240e+02 6.000e+01 ... 3.580e+01 5.140e-01 2.100e+01]
 [0.000e+00 1.070e+02 6.200e+01 ... 3.660e+01 7.570e-01 2.500e+01]
 ...
 [2.000e+00 9.900e+01 0.000e+00 ... 2.220e+01 1.080e-01 2.300e+01]
 [2.000e+00 1.460e+02 7.600e+01 ... 3.820e+01 3.290e-01 2.900e+01]
 [1.100e+01 1.360e+02 8.400e+01 ... 2.830e+01 2.600e-01 4.200e+01]]


In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [34]:
print(X_train)
print(X_test)

[[-1.12825929 -0.10390189 -3.37180661 ...  0.20038747  1.38912194
   0.91171396]
 [-0.24806423 -0.29141361 -0.31344133 ... -1.17369805 -1.01388454
  -1.03421588]
 [ 0.33873247 -2.38529445 -0.31344133 ... -0.87925116  0.33970772
   0.2348688 ]
 ...
 [-0.24806423 -1.85401125  0.67312811 ...  0.2739992  -0.70666472
   1.08092525]
 [-0.83486094 -0.7601929   2.646267   ... -1.1982353  -0.81616882
  -0.52658201]
 [-0.83486094 -0.94770462 -0.31344133 ... -0.86698253  2.41116014
  -0.6957933 ]]
[[-1.18582106  0.73684254  0.66378294 ...  1.29469107  3.90512117
   0.92719383]
 [-0.87731477  0.04396122 -0.70861997 ...  0.62079754  0.15524296
  -1.06428864]
 [-1.18582106 -0.49144707 -0.58385607 ...  0.73550282  0.87443823
  -0.71794386]
 ...
 [-0.56880847 -0.74340391 -4.451537   ... -1.32919227 -1.04637547
  -0.89111625]
 [-0.56880847  0.73684254  0.28949124 ...  0.96491339 -0.39229253
  -0.37159908]
 [ 2.20774815  0.42189648  0.78854684 ... -0.45456449 -0.59650847
   0.75402144]]


In [35]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression()
regressor.fit(X_train, y_train)

LogisticRegression()

In [36]:
y_pred = regressor.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test),1), y_pred.reshape(len(y_pred),1)),1))

[[0 1]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[115  17]
 [ 25  35]]


0.78125

In [42]:
regressor.predict(sc.transform([[6,140,120,23,534,32,0.654, 45]]))

array([0])