In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [5]:
print(X_train)

[[15810075    39000]
 [15583681   120000]
 [15733964    50000]
 [15598840   135000]
 [15663249    21000]
 [15588080   104000]
 [15668385    42000]
 [15721835    61000]
 [15619087    50000]
 [15725794    63000]
 [15710257    25000]
 [15682268    50000]
 [15673539    73000]
 [15736760    49000]
 [15807525    29000]
 [15636023    65000]
 [15815236   131000]
 [15793813    89000]
 [15617877    82000]
 [15629739    51000]
 [15809823    15000]
 [15593715   102000]
 [15619407   112000]
 [15813113   107000]
 [15800215    53000]
 [15617134    59000]
 [15714658    41000]
 [15795298   134000]
 [15800515   113000]
 [15789815   148000]
 [15679651    15000]
 [15635893    42000]
 [15679760    19000]
 [15701537   149000]
 [15666675    96000]
 [15593014    59000]
 [15622585    96000]
 [15689751    89000]
 [15713463    72000]
 [15617482    26000]
 [15697574    69000]
 [15724402    82000]
 [15581198    74000]
 [15739160    80000]
 [15767681    72000]
 [15675949   149000]
 [15573926    71000]
 [15722061   

In [6]:
print(y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [7]:
print(X_test)

[[15725660    87000]
 [15652400    50000]
 [15776844    75000]
 [15738448    79000]
 [15638003    50000]
 [15814004    20000]
 [15610140    15000]
 [15680587   144000]
 [15666141    68000]
 [15622478    43000]
 [15689425    49000]
 [15800061    55000]
 [15773447    55000]
 [15579212    77000]
 [15746139    86000]
 [15789109   117000]
 [15760570    77000]
 [15807909    85000]
 [15654230   130000]
 [15708228    22000]
 [15609653    47000]
 [15746203   144000]
 [15678168    51000]
 [15729908   105000]
 [15614420    28000]
 [15753861   141000]
 [15667265    87000]
 [15697686    80000]
 [15631070    62000]
 [15584545    86000]
 [15587013    88000]
 [15637593    79000]
 [15814553    60000]
 [15622171    53000]
 [15718071    58000]
 [15746737    52000]
 [15684801    81000]
 [15581654    43000]
 [15673367    34000]
 [15594041    36000]
 [15766289    88000]
 [15674331    52000]
 [15598044    84000]
 [15810944    20000]
 [15705298   112000]
 [15654901    58000]
 [15793890    80000]
 [15750056   

In [8]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
print(X_train)

[[ 1.67009484e+00 -8.86706990e-01]
 [-1.52442817e+00  1.46173768e+00]
 [ 5.96133781e-01 -5.67782405e-01]
 [-1.31052773e+00  1.89663484e+00]
 [-4.01687250e-01 -1.40858358e+00]
 [-1.46235626e+00  9.97847375e-01]
 [-3.29215938e-01 -7.99727558e-01]
 [ 4.24988037e-01 -2.48857820e-01]
 [-1.02483329e+00 -5.67782405e-01]
 [ 4.80851340e-01 -1.90871532e-01]
 [ 2.61617156e-01 -1.29261101e+00]
 [-1.33320451e-01 -5.67782405e-01]
 [-2.56490638e-01  9.90599089e-02]
 [ 6.35586622e-01 -5.96775549e-01]
 [ 1.63411318e+00 -1.17663843e+00]
 [-7.85858577e-01 -1.32885244e-01]
 [ 1.74291892e+00  1.78066227e+00]
 [ 1.44063058e+00  5.62950214e-01]
 [-1.04190695e+00  3.59998206e-01]
 [-8.74528695e-01 -5.38789261e-01]
 [ 1.66653901e+00 -1.58254245e+00]
 [-1.38284383e+00  9.39861087e-01]
 [-1.02031795e+00  1.22979253e+00]
 [ 1.71296241e+00  1.08482681e+00]
 [ 1.53096573e+00 -4.80802973e-01]
 [-1.05239102e+00 -3.06844108e-01]
 [ 3.23717281e-01 -8.28720702e-01]
 [ 1.46158461e+00  1.86764170e+00]
 [ 1.53519887e+00  1

In [11]:
print(X_test)

[[ 4.78960539e-01  5.04963926e-01]
 [-5.54771608e-01 -5.67782405e-01]
 [ 1.20119022e+00  1.57046197e-01]
 [ 6.59405075e-01  2.73018773e-01]
 [-7.57919871e-01 -5.67782405e-01]
 [ 1.72553483e+00 -1.43757673e+00]
 [-1.15107956e+00 -1.58254245e+00]
 [-1.57040131e-01  2.15757314e+00]
 [-3.60879806e-01 -4.59058115e-02]
 [-9.76984730e-01 -7.70734413e-01]
 [-3.23319037e-02 -5.96775549e-01]
 [ 1.52879272e+00 -4.22816685e-01]
 [ 1.15325699e+00 -4.22816685e-01]
 [-1.58748780e+00  2.15032485e-01]
 [ 7.67928607e-01  4.75970782e-01]
 [ 1.37425498e+00  1.37475825e+00]
 [ 9.71556625e-01  2.15032485e-01]
 [ 1.63953159e+00  4.46977638e-01]
 [-5.28949470e-01  1.75166912e+00]
 [ 2.32987036e-01 -1.37959044e+00]
 [-1.15795135e+00 -6.54761837e-01]
 [ 7.68831676e-01  2.15757314e+00]
 [-1.91173328e-01 -5.38789261e-01]
 [ 5.38901764e-01  1.02684052e+00]
 [-1.09068680e+00 -1.20563157e+00]
 [ 8.76889563e-01  2.07059371e+00]
 [-3.45019651e-01  5.04963926e-01]
 [ 8.42345892e-02  3.02011918e-01]
 [-8.55747675e-01 -2

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [13]:
print(classifier.predict(sc.transform([[30,87000]])))

[1]


In [14]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(-1,1), y_test.reshape(-1,1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [1 1]]


In [15]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[66  2]
 [19 13]]


0.79